import * as THREE from 'three';
import {GLTFLoader} from './vendor/three/addons/loaders/GLTFLoader.js';
import {RoundedBoxGeometry} from './vendor/three/addons/utils/RoundedBoxGeometry.js';
const host=document.createElement('div');host.id='residence';host.setAttribute('aria-hidden','true');document.querySelector('.scene').prepend(host);
const low=matchMedia('(max-width:700px)').matches || navigator.connection?.saveData;
const state=document.createElement('p');state.className='environment-status';state.textContent='Preparing residence…';host.append(state);
try {
const renderer=new THREE.WebGLRenderer({alpha:true,antialias:!low,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,low?1:1.5));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=!low;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.prepend(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('#c5cccf');const camera=new THREE.PerspectiveCamera(59,innerWidth/innerHeight,.01,100);camera.position.set(2.250,1.312,6.179);camera.quaternion.setFromRotationMatrix(new THREE.Matrix4().fromArray([.900687,0,-.434467,0,-.015915,.999329,-.032993,0,.434175,.036630,.900083,0,2.25,1.312,6.179,1]));scene.add(camera);
scene.add(new THREE.HemisphereLight(0xe8f2ff,0x867560,2.5));const sun=new THREE.DirectionalLight(0xffedcf,3);sun.position.set(-3,6,-4);scene.add(sun);const fill=new THREE.PointLight(0xffd4a0,25,12,2);fill.position.set(1,2.5,2);scene.add(fill);
const loader=new GLTFLoader();let renderPending=false;
function render(){renderPending=false;renderer.render(scene,camera)}
function invalidate(){if(!renderPending){renderPending=true;requestAnimationFrame(render)}}
const room=await loader.loadAsync('./assets/room/residence.glb');room.scene.traverse(o=>{if(o.isMesh){o.receiveShadow=true;const m=o.material;if(m.name==='TvScreen'){m.color.set('#152035');m.emissive.set('#1b304a');m.emissiveIntensity=.3}}});scene.add(room.scene);
// A detailed, bevelled workstation, authored for this scene. Small repeated parts
// use instancing; figures below use licensed meshes, never primitive mannequins.
const desk=new THREE.Group();desk.position.set(0,-.95,-2.5);camera.add(desk);
const material=(color,roughness=.5,metalness=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness});
const charcoal=material('#1c2024',.38,.45), aluminium=material('#4b5156',.25,.8), ivory=material('#cfcdc7',.48), rubber=material('#11151a',.9);
function bevel(w,h,d,r,mat,x,y,z,parent=desk){const m=new THREE.Mesh(new RoundedBoxGeometry(w,h,d,3,r),mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
function cylinder(r1,r2,h,mat,x,y,z,parent=desk){const m=new THREE.Mesh(new THREE.CylinderGeometry(r1,r2,h,48),mat);m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m}
const woodCanvas=document.createElement('canvas');woodCanvas.width=1024;woodCanvas.height=256;const ctx=woodCanvas.getContext('2d');ctx.fillStyle='#684d37';ctx.fillRect(0,0,1024,256);let seed=15;const random=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);for(let i=0;i<1800;i++){ctx.strokeStyle=`rgba(${random()>.5?'211,169,107':'37,22,13'},${random()*.14})`;ctx.beginPath();const y=random()*256;ctx.moveTo(0,y);ctx.bezierCurveTo(350,y+random()*6,700,y-random()*5,1024,y+random()*4);ctx.stroke()}
const wood=new THREE.CanvasTexture(woodCanvas);wood.colorSpace=THREE.SRGBColorSpace;wood.wrapS=wood.wrapT=THREE.RepeatWrapping;const walnut=material('#c9b8a3',.47);walnut.map=wood;
bevel(4,.085,1.5,.035,walnut,0,0,0);bevel(.12,1.4,1.2,.03,charcoal,-1.65,-.73,0);bevel(.12,1.4,1.2,.03,charcoal,1.65,-.73,0);bevel(2.15,.012,.63,.06,rubber,-.2,.05,.35);
// Ultrawide aluminium display with a colourful, original contour wallpaper.
bevel(1.55,.68,.047,.035,charcoal,-.95,.66,-.49);bevel(.055,.32,.065,.015,aluminium,-.95,.25,-.48);bevel(.45,.026,.24,.025,aluminium,-.95,.06,-.45);
const wallpaper=document.createElement('canvas');wallpaper.width=1024;wallpaper.height=440;const wc=wallpaper.getContext('2d');const grad=wc.createLinearGradient(0,0,1024,440);grad.addColorStop(0,'#102c43');grad.addColorStop(.5,'#42748d');grad.addColorStop(1,'#edaf85');wc.fillStyle=grad;wc.fillRect(0,0,1024,440);for(let j=0;j<16;j++){wc.strokeStyle=`rgba(235,233,232,${.04+j*.005})`;wc.lineWidth=12;wc.beginPath();wc.ellipse(700,350,160+j*24,90+j*18,-.5,0,Math.PI*2);wc.stroke()}const wt=new THREE.CanvasTexture(wallpaper);wt.colorSpace=THREE.SRGBColorSpace;bevel(1.49,.62,.006,.018,new THREE.MeshBasicMaterial({map:wt}),-.95,.66,-.463);
// Mechanical keyboard: sculpted keycaps are instanced instead of separate draw calls.
bevel(.85,.04,.28,.03,aluminium,-.78,.087,.36);const keys=new THREE.InstancedMesh(new RoundedBoxGeometry(.044,.024,.042,2,.007),ivory,70);let n=0;const matrix=new THREE.Matrix4();for(let row=0;row<5;row++)for(let col=0;col<14;col++)keys.setMatrixAt(n++,matrix.makeTranslation(-1.16+col*.057,.118,.25+row*.052));desk.add(keys);bevel(.27,.025,.04,.006,ivory,-.76,.12,.485);const mouse=new THREE.Mesh(new THREE.SphereGeometry(1,32,20),ivory);mouse.scale.set(.064,.031,.095);mouse.position.set(-.2,.095,.36);desk.add(mouse);bevel(.009,.009,.028,.004,charcoal,-.2,.126,.33);
// Tempered-glass tower, chassis rails, internal board and RGB fan rings.
bevel(.38,.66,.55,.024,charcoal,1.31,.38,-.27);const glass=new THREE.MeshPhysicalMaterial({color:'#98b2c6',transparent:true,opacity:.18,roughness:.13,metalness:.2,depthWrite:false});bevel(.385,.59,.48,.014,glass,1.31,.4,-.23);for(let i=0;i<3;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.067,.006,8,48),new THREE.MeshStandardMaterial({color:i===1?'#8978c0':'#759fbb',emissive:i===1?'#67529e':'#447696',emissiveIntensity:1.3}));ring.position.set(1.31,.19+i*.18,.011);desk.add(ring);const hub=cylinder(.02,.02,.02,charcoal,1.31,.19+i*.18,.006);hub.rotation.x=Math.PI/2;}bevel(.24,.34,.012,.006,aluminium,1.31,.38,-.29);
// Studio speakers with recessed drivers and fine concentric suspension rings.
for(const x of [-1.89,.03]){bevel(.19,.3,.2,.019,charcoal,x,.22,-.43);for(const [y,r]of [[.19,.056],[.31,.024]]){const driver=cylinder(r,r,.018,rubber,x,y,-.322);driver.rotation.x=Math.PI/2;const rim=new THREE.Mesh(new THREE.TorusGeometry(r,.004,8,40),aluminium);rim.position.set(x,y,-.31);desk.add(rim)}}
// Headphones with a curved padded headband and articulated ear cups.
const headband=new THREE.Mesh(new THREE.TorusGeometry(.14,.014,10,48,Math.PI),charcoal);headband.position.set(.55,.38,-.37);desk.add(headband);for(const x of [.41,.69]){bevel(.045,.13,.075,.022,charcoal,x,.31,-.37);bevel(.019,.11,.06,.009,rubber,x+(x<.5?.025:-.025),.31,-.37)}cylinder(.065,.085,.018,aluminium,.55,.067,-.37);bevel(.02,.25,.024,.006,aluminium,.55,.2,-.37);
// Cable routing follows a spline below the rear desk edge.
const cableCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(-.95,.1,-.5),new THREE.Vector3(-.95,-.08,-.65),new THREE.Vector3(.5,-.1,-.65),new THREE.Vector3(1.3,.1,-.5)]);desk.add(new THREE.Mesh(new THREE.TubeGeometry(cableCurve,24,.008,6,false),rubber));
const keyLight=new THREE.SpotLight(0xffe2b5,32,10,.9,.7);keyLight.position.set(-1,3,1);keyLight.target=desk;keyLight.castShadow=!low;keyLight.shadow.mapSize.set(1024,1024);camera.add(keyLight);const rimLight=new THREE.PointLight(0x778bcc,1.3,3);rimLight.position.set(1,.5,-.7);desk.add(rimLight);
async function figure(url,x,height,angle){try{const g=(await loader.loadAsync(url)).scene;const bounds=new THREE.Box3().setFromObject(g),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3());const holder=new THREE.Group();g.scale.setScalar(height/size.y);g.position.set(-center.x*height/size.y,-bounds.min.y*height/size.y,-center.z*height/size.y);holder.add(g);holder.position.set(x,.09,-.45);holder.rotation.y=angle;desk.add(holder);cylinder(.105,.12,.026,charcoal,x,.067,-.45);invalidate()}catch(e){state.textContent='One collectible could not load.';console.warn('Collectible unavailable',e)}}
await Promise.allSettled([figure('./assets/figures/astronaut.glb',.28,.36,-.25),figure('./assets/figures/robot.glb',.93,.34,-.4)]);
state.textContent='';document.body.classList.add('residence-ready');invalidate();
let px=0,py=0;const originalQ=camera.quaternion.clone();window.addEventListener('pointermove',e=>{if(low||matchMedia('(prefers-reduced-motion:reduce)').matches)return;px=(e.clientX/innerWidth-.5)*.008;py=(e.clientY/innerHeight-.5)*.005;camera.quaternion.copy(originalQ).multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(py,px,0)));invalidate()},{passive:true});window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);invalidate()});document.addEventListener('visibilitychange',()=>{if(!document.hidden)invalidate()});renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();document.body.classList.remove('residence-ready');state.textContent='3D paused. Reload to restore the residence.'});
} catch(error){state.textContent='Residence unavailable · lightweight room shown';console.warn('Residence fallback',error)}
