/* Browser-compatible system interactions. Native services are never impersonated. */
(() => {
 const screen=document.querySelector('.screen');
 const read=(k,f)=>{try{return localStorage.getItem(k)??f}catch{return f}};
 const save=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const panel=document.createElement('section');panel.className='os-panel';panel.id='systemPanel';panel.setAttribute('aria-label','System app');screen.append(panel);
 const overlay=document.createElement('section');overlay.className='os-panel';overlay.id='systemOverlay';screen.append(overlay);
 let current='',previousFocus=null;
 function home(){panel.classList.remove('open');overlay.classList.remove('open');closePhotos();closeSafari();current='';previousFocus?.focus()}
 function bind(el,sel,event,fn){el.querySelector(sel)?.addEventListener(event,fn)}
 function shell(title,body){return `<nav class="os-nav"><button data-home>‹ Home</button><strong>${title}</strong><button data-lock aria-label="Lock screen">Lock</button></nav>${body}`}
 function show(title,body){previousFocus=document.activeElement;closePhotos();closeSafari();overlay.classList.remove('open');panel.innerHTML=shell(title,body);panel.classList.add('open');panel.scrollTop=0;current=title;bind(panel,'[data-home]','click',home);bind(panel,'[data-lock]','click',lock);stopFloat()}
 function settings(){show('Settings',`<h2>Settings</h2><div class="os-card"><h3>Appearance</h3><label class="os-row">Dark appearance<input id="darkMode" type="checkbox" ${screen.classList.contains('dark-ui')?'checked':''}></label><p>Liquid Glass</p><input id="glassAmount" aria-label="Liquid Glass tint" type="range" min="0" max="100" value="${read('glass','25')}"><div class="os-row"><small>Ultra-clear</small><small>Tinted</small></div></div><div class="os-card"><p>Display brightness</p><input id="brightness" aria-label="Display brightness" type="range" min="45" max="100" value="100"></div><div class="os-card"><h3>About this experience</h3><p>Lovely iPhone · iOS-inspired web simulation.</p><p class="os-muted">Connectivity switches are simulated. Calls, Apple services and Siri AI are not connected.</p></div>`);bind(panel,'#darkMode','change',e=>{screen.classList.toggle('dark-ui',e.target.checked);save('dark',e.target.checked)});bind(panel,'#glassAmount','input',e=>{root.style.setProperty('--glass-tint',.08+e.target.value*.007);save('glass',e.target.value)});bind(panel,'#brightness','input',e=>screen.style.filter=`brightness(${e.target.value}%)`)}
 function lock(){overlay.className='os-panel os-lock open';overlay.innerHTML=`<div>♧</div><p>${escape(new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'}))}</p><time>${escape(document.getElementById('statusTime').textContent)}</time><div class="os-card"><strong>Welcome home</strong><p>Your villa. Your little world.</p></div><button class="os-primary" id="unlock">Unlock</button><p class="os-muted" style="color:#fff">Swipe up to unlock</p>`;bind(overlay,'#unlock','click',()=>overlay.classList.remove('open'))}
 const connections={WiFi:true,Bluetooth:true,'Airplane mode':false,Focus:false};
 function controls(){overlay.className='os-panel os-control open';overlay.innerHTML=`<nav class="os-nav"><strong>Control Center</strong><button id="dismiss">Done</button></nav><h2>Make it yours.</h2><div class="os-grid">${Object.entries(connections).map(([k,v])=>`<button class="os-tile ${v?'active':''}" data-connect="${k}">${k}<small>${v?'On':'Off'} · simulated</small></button>`).join('')}</div><div class="os-card system-glass"><p>Brightness</p><input aria-label="Brightness" id="ccBrightness" type="range" min="45" max="100" value="100"></div><button class="os-tile" id="ccAppearance">◐ &nbsp; Appearance</button>`;bind(overlay,'#dismiss','click',()=>overlay.classList.remove('open'));overlay.querySelectorAll('[data-connect]').forEach(b=>b.onclick=()=>{connections[b.dataset.connect]=!connections[b.dataset.connect];controls()});bind(overlay,'#ccBrightness','input',e=>screen.style.filter=`brightness(${e.target.value}%)`);bind(overlay,'#ccAppearance','click',settings)}
 function notifications(){overlay.className='os-panel os-control open';overlay.innerHTML=`<nav class="os-nav"><strong>Notification Center</strong><button id="dismiss">Done</button></nav><h2>${escape(document.getElementById('statusTime').textContent)}</h2><div id="notice" class="os-card system-glass"><strong>Lovely iPhone</strong><p>Explore Photos, personalise Liquid Glass, or write a note.</p><button class="os-primary" id="clearNotice">Clear</button></div>`;bind(overlay,'#dismiss','click',()=>overlay.classList.remove('open'));bind(overlay,'#clearNotice','click',()=>{overlay.querySelector('#notice').innerHTML='<p>No notifications</p>'})}
 function app(name){
 if(name==='Settings')return settings();
 if(name==='Notes'){show(name,`<h2>Notes</h2><p class="os-muted">Saved on this browser</p><textarea id="note" aria-label="Your note" placeholder="A little idea…">${escape(read('note',''))}</textarea><p id="saved" class="os-muted">All changes saved locally</p>`);bind(panel,'#note','input',e=>save('note',e.target.value));}
 else if(name==='Clock'){show(name,`<h2>World Clock</h2>${['America/Los_Angeles','Asia/Tehran','Europe/London'].map(z=>`<div class="os-card"><small>${z.split('/')[1].replaceAll('_',' ')}</small><h2>${new Date().toLocaleTimeString('en-US',{timeZone:z,hour:'2-digit',minute:'2-digit'})}</h2></div>`).join('')}<button class="os-primary" id="refreshClock">Refresh</button>`);bind(panel,'#refreshClock','click',()=>app(name))}
 else if(name==='Health'){show(name,`<h2>How are you?</h2><div class="os-card"><h3>State of Mind</h3><p>A moment to check in with yourself.</p><div class="os-grid">${['Great','Good','Okay','Low'].map(x=>`<button class="os-tile" data-mood="${x}">${x}</button>`).join('')}</div><p id="mood">${escape(read('mood','Choose your mood'))}</p></div><p class="os-muted">Personal journal only. No health sensors are connected.</p>`);panel.querySelectorAll('[data-mood]').forEach(b=>b.onclick=()=>{save('mood',b.dataset.mood);panel.querySelector('#mood').textContent=b.dataset.mood+' · saved'})}
 else if(name==='Phone'){show(name,`<h2>Phone</h2><div class="os-number" id="number"></div><div class="os-dial">${'123456789*0#'.split('').map(n=>`<button data-digit="${n}">${n}</button>`).join('')}</div><button id="dial" class="os-primary">Open dialler</button> <button id="erase">⌫</button><p class="os-muted">Uses your device’s phone app if available.</p>`);panel.querySelectorAll('[data-digit]').forEach(b=>b.onclick=()=>panel.querySelector('#number').textContent+=b.dataset.digit);bind(panel,'#erase','click',()=>panel.querySelector('#number').textContent=panel.querySelector('#number').textContent.slice(0,-1));bind(panel,'#dial','click',()=>{const n=panel.querySelector('#number').textContent;if(n)location.href='tel:'+encodeURIComponent(n)})}
 else if(name==='Messages'){show(name,`<h2>Messages</h2><p class="os-muted">Local demo conversation · nothing is sent</p><div id="messages"><div class="os-message">Welcome to Lovely iPhone.</div></div><input id="message" type="text" aria-label="Message" placeholder="iMessage demo"><button class="os-primary" id="send" style="margin-top:12px">Add message</button>`);bind(panel,'#send','click',()=>{const i=panel.querySelector('#message');if(!i.value.trim())return;const p=document.createElement('div');p.className='os-message';p.textContent=i.value;panel.querySelector('#messages').append(p);i.value=''})}
 else if(name==='Mail'){show(name,`<h2>New Message</h2><p class="os-muted">Compose in your device’s email app.</p><input type="text" id="subject" aria-label="Subject" placeholder="Subject"><textarea id="mailBody" aria-label="Email body" placeholder="Your message" style="margin:12px 0"></textarea><button id="compose" class="os-primary">Open mail app</button>`);bind(panel,'#compose','click',()=>location.href='mailto:?subject='+encodeURIComponent(panel.querySelector('#subject').value)+'&body='+encodeURIComponent(panel.querySelector('#mailBody').value))}
 else if(name==='Maps'){show(name,`<h2>Explore</h2><div class="os-card"><h3>Where would you like to go?</h3><input type="text" id="place" aria-label="Place" placeholder="California"><p>Search a location in Apple Maps.</p><button class="os-primary" id="mapSearch">Open Maps ↗</button></div>`);bind(panel,'#mapSearch','click',()=>window.open('https://maps.apple.com/?q='+encodeURIComponent(panel.querySelector('#place').value||'California'),'_blank','noopener,noreferrer'))}
 else if(name==='Music'){show(name,`<h2>Your music</h2><div class="os-card"><h3>Bring your soundtrack.</h3><p>Choose an audio file from your device. It stays in this browser.</p><input id="audioFile" aria-label="Choose music" type="file" accept="audio/*"><audio class="os-player" controls id="audioPlayer"></audio></div>`);bind(panel,'#audioFile','change',e=>{const f=e.target.files[0];if(f){const a=panel.querySelector('audio');if(a.src)URL.revokeObjectURL(a.src);a.src=URL.createObjectURL(f)}})}
 else if(name==='Camera'){show(name,`<h2>Camera</h2><div class="os-card"><p>Select or take a photo using your device.</p><input id="cameraFile" aria-label="Take or choose a photo" type="file" accept="image/*" capture="environment"><img id="cameraPreview" alt="Your selected photo" style="display:none;width:100%;border-radius:16px;margin-top:15px"></div>`);bind(panel,'#cameraFile','change',e=>{const f=e.target.files[0];if(f){const im=panel.querySelector('img');if(im.src)URL.revokeObjectURL(im.src);im.src=URL.createObjectURL(f);im.style.display='block'}})}
 }
 document.querySelectorAll('.app').forEach(el=>{el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label','Open '+el.dataset.app);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click()}});if(!['Photos','Safari'].includes(el.dataset.app))el.addEventListener('click',e=>{e.stopImmediatePropagation();toast.classList.remove('show');app(el.dataset.app)},true)});
 [panel,overlay].forEach(el=>['pointerdown','pointermove','wheel','dblclick'].forEach(ev=>el.addEventListener(ev,e=>e.stopPropagation())));
 document.querySelector('.homebar').onclick=home;document.querySelector('.homebar').setAttribute('aria-label','Go Home');document.querySelector('.homebar').setAttribute('role','button');document.querySelector('.homebar').tabIndex=0;document.querySelector('.homebar').onkeydown=e=>{if(e.key==='Enter')home()};
 document.querySelector('.signals').onclick=controls;document.querySelector('#statusTime').onclick=notifications;
 const toolbar=document.createElement('nav');toolbar.className='system-toolbar';toolbar.setAttribute('aria-label','Device controls');toolbar.innerHTML='<button id="viewFront">Front</button><button id="viewBack">Back</button><button id="systemHome">Home</button><button id="systemLock">Lock</button><button id="systemControls">Controls</button>';document.body.append(toolbar);
 bind(toolbar,'#viewFront','click',()=>{rx=0;ry=0;zoom=1;apply()});bind(toolbar,'#viewBack','click',()=>{rx=0;ry=180;apply()});bind(toolbar,'#systemHome','click',home);bind(toolbar,'#systemLock','click',lock);bind(toolbar,'#systemControls','click',controls);
 let startY=0;overlay.addEventListener('pointerdown',e=>startY=e.clientY);overlay.addEventListener('pointerup',e=>{if(startY-e.clientY>45)overlay.classList.remove('open')});
 document.addEventListener('keydown',e=>{if(e.key==='Escape')home()});
 screen.classList.toggle('dark-ui',read('dark','false')==='true');root.style.setProperty('--glass-tint',.08+Number(read('glass','25'))*.007);
 const status=document.createElement('div');status.className='asset-status';status.setAttribute('role','status');document.body.append(status);status.textContent='Loading original iPhone model…';physicalPhone.addEventListener('load',()=>status.textContent='');physicalPhone.addEventListener('error',()=>status.textContent='3D model unavailable. Interactive 2D mode is active.');if(physicalPhone.loaded)status.textContent='';
})();
